print('----------------------------------------')
print('| Naaminvoer ')
name = input('| Geef jouw naam ')
print('| Hallo ' + name)
print("| ")
print('| Adresinvoer')
adres = input('| Geef jouw adres')
print('| Adres ' + adres)
print("| ")
print('| Postcodeinvoer')
postcode = input('| Geef jouw postcode')
print('| Postcode ' + postcode)
print("| ")
print('| Woonplaatsinvoer')
woonplaats = input('| Geef jouw woonplaats')
print('| Woonplaats ' + woonplaats)
print('----------------------------------------')